function Grad_Sigma_V = Grad_Sigma_V_FT_XYZ_7NN(X,alpha)
%Grad_Sigma_V
%    Grad_Sigma_V = Grad_Sigma_V(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-09-26 11:06:18

x1 = X(1,:);
x2 = X(2,:);
x3 = X(3,:);

% Grad_Sigma_V = [(abs(x1)^alpha)*sign(x1), 0, 0;
%                 0, (abs(x2)^alpha)*sign(x2), 0;
%                 (abs(x1)^alpha)*sign(x1), (abs(x2)^alpha)*sign(x2), 0;
%                 0, 0, (abs(x3)^alpha)*sign(x3);
%                 (abs(x1)^alpha)*sign(x1), 0, (abs(x3)^alpha)*sign(x3);
%                 0, (abs(x2)^alpha)*sign(x2), (abs(x3)^alpha)*sign(x3);
%                 (abs(x1)^alpha)*sign(x1), (abs(x2)^alpha)*sign(x2), (abs(x3)^alpha)*sign(x3)];
Grad_Sigma_V = [(abs(x1)^alpha)*sign(x1), 0, 0;
                0, (abs(x2)^alpha)*sign(x2), 0;
                0, 0, (abs(x3)^alpha)*sign(x3);
                (abs(x1)^alpha)*sign(x1), (abs(x2)^alpha)*sign(x2), 0;
                (abs(x1)^alpha)*sign(x1), 0, (abs(x3)^alpha)*sign(x3);
                0, (abs(x2)^alpha)*sign(x2), (abs(x3)^alpha)*sign(x3);
                (abs(x1)^alpha)*sign(x1), (abs(x2)^alpha)*sign(x2), (abs(x3)^alpha)*sign(x3)];
end




























